name: Build menu site every 3 days

on:
  schedule:
    - cron: "0 0 */3 * *"   # UTC 자정, 3일마다
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build & Generate site
        run: mvn -q -DskipTests compile exec:java

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: refresh menu site"
            git push
          fi
