name: Build menu site every 3 days

on:
  schedule:
    - cron: "0 23 * * *"   # 매일 23:00 UTC = KST 매일 오전 8시
  workflow_dispatch:


permissions:
  contents: write  # 자동 커밋/푸시 권한

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0           # 푸시/리베이스 시 필요할 수 있음

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven             # Maven 캐시

      - name: Show tool versions (debug)
        run: |
          java -version
          mvn -v

      - name: Build & Generate site
        run: mvn -q -DskipTests compile exec:java

      - name: Check generated files (debug)
        run: |
          ls -la docs || true
          test -f docs/index.html && echo "index.html OK" || (echo "index.html missing" && exit 1)

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: refresh menu site"
            git push
          fi
